# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\BannerDesigner.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_BannerDesigner(object):
    def setupUi(self, BannerDesigner):
        BannerDesigner.setObjectName("BannerDesigner")
        BannerDesigner.resize(1200, 600)
        self.scrollArea = QtWidgets.QScrollArea(BannerDesigner)
        self.scrollArea.setGeometry(QtCore.QRect(825, 100, 350, 450))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 348, 448))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayoutWidget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(-1, -1, 351, 451))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.GridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.GridLayout.setContentsMargins(0, 0, 0, 0)
        self.GridLayout.setObjectName("GridLayout")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.RowSpinBox = QtWidgets.QSpinBox(BannerDesigner)
        self.RowSpinBox.setGeometry(QtCore.QRect(900, 20, 81, 21))
        self.RowSpinBox.setMinimum(2)
        self.RowSpinBox.setMaximum(64)
        self.RowSpinBox.setObjectName("RowSpinBox")
        self.RowLabel = QtWidgets.QLabel(BannerDesigner)
        self.RowLabel.setGeometry(QtCore.QRect(830, 20, 71, 21))
        self.RowLabel.setObjectName("RowLabel")
        self.ColumnSpinBox = QtWidgets.QSpinBox(BannerDesigner)
        self.ColumnSpinBox.setGeometry(QtCore.QRect(900, 60, 81, 21))
        self.ColumnSpinBox.setMinimum(2)
        self.ColumnSpinBox.setMaximum(64)
        self.ColumnSpinBox.setObjectName("ColumnSpinBox")
        self.ColumnLabel = QtWidgets.QLabel(BannerDesigner)
        self.ColumnLabel.setGeometry(QtCore.QRect(830, 60, 71, 21))
        self.ColumnLabel.setObjectName("ColumnLabel")

        self.retranslateUi(BannerDesigner)
        QtCore.QMetaObject.connectSlotsByName(BannerDesigner)

    def retranslateUi(self, BannerDesigner):
        _translate = QtCore.QCoreApplication.translate
        BannerDesigner.setWindowTitle(_translate("BannerDesigner", "BannerDesigner"))
        BannerDesigner.setStyleSheet(_translate("BannerDesigner", "QGroupBox { font-weight: bold; }"))
        self.RowLabel.setText(_translate("BannerDesigner", "行数"))
        self.ColumnLabel.setText(_translate("BannerDesigner", "列数"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    BannerDesigner = QtWidgets.QWidget()
    ui = Ui_BannerDesigner()
    ui.setupUi(BannerDesigner)
    BannerDesigner.show()
    sys.exit(app.exec_())
