# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\BannerDesigner.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_BannerDesigner(object):
    def setupUi(self, BannerDesigner):
        BannerDesigner.setObjectName("BannerDesigner")
        BannerDesigner.resize(1200, 700)
        self.scrollArea = QtWidgets.QScrollArea(BannerDesigner)
        self.scrollArea.setGeometry(QtCore.QRect(825, 200, 350, 450))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 348, 448))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayoutWidget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(-1, -1, 351, 451))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.GridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.GridLayout.setContentsMargins(0, 0, 0, 0)
        self.GridLayout.setObjectName("GridLayout")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.RowSpinBox = QtWidgets.QSpinBox(BannerDesigner)
        self.RowSpinBox.setGeometry(QtCore.QRect(900, 120, 81, 21))
        self.RowSpinBox.setMinimum(2)
        self.RowSpinBox.setMaximum(64)
        self.RowSpinBox.setObjectName("RowSpinBox")
        self.RowLabel = QtWidgets.QLabel(BannerDesigner)
        self.RowLabel.setGeometry(QtCore.QRect(830, 120, 71, 21))
        self.RowLabel.setObjectName("RowLabel")
        self.ColumnSpinBox = QtWidgets.QSpinBox(BannerDesigner)
        self.ColumnSpinBox.setGeometry(QtCore.QRect(900, 160, 81, 21))
        self.ColumnSpinBox.setMinimum(2)
        self.ColumnSpinBox.setMaximum(64)
        self.ColumnSpinBox.setObjectName("ColumnSpinBox")
        self.ColumnLabel = QtWidgets.QLabel(BannerDesigner)
        self.ColumnLabel.setGeometry(QtCore.QRect(830, 160, 71, 21))
        self.ColumnLabel.setObjectName("ColumnLabel")
        self.FilepathTxtLabel = QtWidgets.QLabel(BannerDesigner)
        self.FilepathTxtLabel.setGeometry(QtCore.QRect(30, 20, 71, 21))
        self.FilepathTxtLabel.setObjectName("FilepathTxtLabel")
        self.FilePathLabel = QtWidgets.QLabel(BannerDesigner)
        self.FilePathLabel.setGeometry(QtCore.QRect(130, 20, 341, 61))
        self.FilePathLabel.setText("")
        self.FilePathLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.FilePathLabel.setObjectName("FilePathLabel")
        self.OpenFileButton = QtWidgets.QPushButton(BannerDesigner)
        self.OpenFileButton.setGeometry(QtCore.QRect(640, 10, 100, 40))
        self.OpenFileButton.setObjectName("OpenFileButton")
        self.DesignSelectComboBox = QtWidgets.QComboBox(BannerDesigner)
        self.DesignSelectComboBox.setGeometry(QtCore.QRect(130, 70, 191, 31))
        self.DesignSelectComboBox.setObjectName("DesignSelectComboBox")
        self.DesignSelectLabel = QtWidgets.QLabel(BannerDesigner)
        self.DesignSelectLabel.setGeometry(QtCore.QRect(30, 70, 71, 21))
        self.DesignSelectLabel.setObjectName("DesignSelectLabel")
        self.NewDesignLabel = QtWidgets.QLabel(BannerDesigner)
        self.NewDesignLabel.setGeometry(QtCore.QRect(360, 70, 71, 21))
        self.NewDesignLabel.setObjectName("NewDesignLabel")
        self.NewDesignTextEdit = QtWidgets.QPlainTextEdit(BannerDesigner)
        self.NewDesignTextEdit.setGeometry(QtCore.QRect(450, 70, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.NewDesignTextEdit.setFont(font)
        self.NewDesignTextEdit.setObjectName("NewDesignTextEdit")
        self.NewDesignButton = QtWidgets.QPushButton(BannerDesigner)
        self.NewDesignButton.setGeometry(QtCore.QRect(640, 60, 100, 40))
        self.NewDesignButton.setObjectName("NewDesignButton")
        self.SaveFileButton = QtWidgets.QPushButton(BannerDesigner)
        self.SaveFileButton.setGeometry(QtCore.QRect(760, 10, 100, 40))
        self.SaveFileButton.setObjectName("SaveFileButton")
        self.CommandButton = QtWidgets.QPushButton(BannerDesigner)
        self.CommandButton.setGeometry(QtCore.QRect(940, 60, 100, 40))
        self.CommandButton.setObjectName("CommandButton")
        self.DisplayButton = QtWidgets.QPushButton(BannerDesigner)
        self.DisplayButton.setGeometry(QtCore.QRect(940, 10, 100, 40))
        self.DisplayButton.setObjectName("DisplayButton")
        self.RealMarginCheckBox = QtWidgets.QCheckBox(BannerDesigner)
        self.RealMarginCheckBox.setGeometry(QtCore.QRect(1060, 10, 101, 40))
        self.RealMarginCheckBox.setObjectName("RealMarginCheckBox")

        self.retranslateUi(BannerDesigner)
        QtCore.QMetaObject.connectSlotsByName(BannerDesigner)

    def retranslateUi(self, BannerDesigner):
        _translate = QtCore.QCoreApplication.translate
        BannerDesigner.setWindowTitle(_translate("BannerDesigner", "BannerDesigner"))
        BannerDesigner.setStyleSheet(_translate("BannerDesigner", "QGroupBox { font-weight: bold; }"))
        self.RowLabel.setText(_translate("BannerDesigner", "行数"))
        self.ColumnLabel.setText(_translate("BannerDesigner", "列数"))
        self.FilepathTxtLabel.setText(_translate("BannerDesigner", "文件路径："))
        self.OpenFileButton.setText(_translate("BannerDesigner", "打开文件"))
        self.DesignSelectLabel.setText(_translate("BannerDesigner", "当前设计："))
        self.NewDesignLabel.setText(_translate("BannerDesigner", "新建设计："))
        self.NewDesignButton.setText(_translate("BannerDesigner", "添加"))
        self.SaveFileButton.setText(_translate("BannerDesigner", "保存文件"))
        self.CommandButton.setText(_translate("BannerDesigner", "生成指令"))
        self.DisplayButton.setText(_translate("BannerDesigner", "预览效果"))
        self.RealMarginCheckBox.setText(_translate("BannerDesigner", "真实间距"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    BannerDesigner = QtWidgets.QWidget()
    ui = Ui_BannerDesigner()
    ui.setupUi(BannerDesigner)
    BannerDesigner.show()
    sys.exit(app.exec_())
