# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\PatternSelector.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PatternSelector(object):
    def setupUi(self, PatternSelector):
        PatternSelector.setObjectName("PatternSelector")
        PatternSelector.resize(350, 250)
        self.Index = QtWidgets.QLabel(PatternSelector)
        self.Index.setGeometry(QtCore.QRect(150, 10, 41, 31))
        self.Index.setObjectName("Index")
        self.ColorComboBox = QtWidgets.QComboBox(PatternSelector)
        self.ColorComboBox.setGeometry(QtCore.QRect(140, 210, 141, 31))
        self.ColorComboBox.setObjectName("ColorComboBox")
        self.ColorHintLabel = QtWidgets.QLabel(PatternSelector)
        self.ColorHintLabel.setGeometry(QtCore.QRect(20, 210, 80, 30))
        self.ColorHintLabel.setObjectName("ColorHintLabel")
        self.scrollArea = QtWidgets.QScrollArea(PatternSelector)
        self.scrollArea.setGeometry(QtCore.QRect(20, 50, 311, 151))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 309, 149))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayoutWidget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 311, 151))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.PatternStyleGLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.PatternStyleGLayout.setContentsMargins(0, 0, 0, 0)
        self.PatternStyleGLayout.setObjectName("PatternStyleGLayout")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.PatternHintLabel = QtWidgets.QLabel(PatternSelector)
        self.PatternHintLabel.setGeometry(QtCore.QRect(20, 10, 80, 30))
        self.PatternHintLabel.setObjectName("PatternHintLabel")
        self.UpButton = QtWidgets.QPushButton(PatternSelector)
        self.UpButton.setGeometry(QtCore.QRect(210, 10, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.UpButton.setFont(font)
        self.UpButton.setObjectName("UpButton")
        self.DownButton = QtWidgets.QPushButton(PatternSelector)
        self.DownButton.setGeometry(QtCore.QRect(260, 10, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.DownButton.setFont(font)
        self.DownButton.setObjectName("DownButton")
        self.DeleteButton = QtWidgets.QPushButton(PatternSelector)
        self.DeleteButton.setGeometry(QtCore.QRect(310, 10, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.DeleteButton.setFont(font)
        self.DeleteButton.setStyleSheet("background-color:red")
        self.DeleteButton.setObjectName("DeleteButton")

        self.retranslateUi(PatternSelector)
        QtCore.QMetaObject.connectSlotsByName(PatternSelector)

    def retranslateUi(self, PatternSelector):
        _translate = QtCore.QCoreApplication.translate
        PatternSelector.setWindowTitle(_translate("PatternSelector", "PatternSelector"))
        PatternSelector.setStyleSheet(_translate("PatternSelector", "QGroupBox { font-weight: bold; }"))
        self.Index.setText(_translate("PatternSelector", "0"))
        self.ColorHintLabel.setText(_translate("PatternSelector", "图案颜色"))
        self.PatternHintLabel.setText(_translate("PatternSelector", "图案样式"))
        self.UpButton.setText(_translate("PatternSelector", "▲"))
        self.DownButton.setText(_translate("PatternSelector", "▼"))
        self.DeleteButton.setText(_translate("PatternSelector", "×"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PatternSelector = QtWidgets.QWidget()
    ui = Ui_PatternSelector()
    ui.setupUi(PatternSelector)
    PatternSelector.show()
    sys.exit(app.exec_())
