# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\SingleBannerDesigner.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SingleBannerDesigner(object):
    def setupUi(self, SingleBannerDesigner):
        SingleBannerDesigner.setObjectName("SingleBannerDesigner")
        SingleBannerDesigner.resize(800, 600)
        self.BannerPainter = QtWidgets.QWidget(SingleBannerDesigner)
        self.BannerPainter.setGeometry(QtCore.QRect(40, 40, 200, 400))
        self.BannerPainter.setObjectName("BannerPainter")
        self.BannerColorComboBox = QtWidgets.QComboBox(SingleBannerDesigner)
        self.BannerColorComboBox.setGeometry(QtCore.QRect(370, 40, 161, 31))
        self.BannerColorComboBox.setObjectName("BannerColorComboBox")
        self.BannerColorLabel = QtWidgets.QLabel(SingleBannerDesigner)
        self.BannerColorLabel.setGeometry(QtCore.QRect(270, 40, 80, 30))
        self.BannerColorLabel.setObjectName("BannerColorLabel")
        self.scrollArea = QtWidgets.QScrollArea(SingleBannerDesigner)
        self.scrollArea.setGeometry(QtCore.QRect(270, 100, 501, 451))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 499, 449))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 501, 451))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.PatternVLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.PatternVLayout.setContentsMargins(0, 0, 0, 0)
        self.PatternVLayout.setObjectName("PatternVLayout")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.SaveButton = QtWidgets.QPushButton(SingleBannerDesigner)
        self.SaveButton.setGeometry(QtCore.QRect(90, 480, 100, 40))
        self.SaveButton.setObjectName("SaveButton")

        self.retranslateUi(SingleBannerDesigner)
        QtCore.QMetaObject.connectSlotsByName(SingleBannerDesigner)

    def retranslateUi(self, SingleBannerDesigner):
        _translate = QtCore.QCoreApplication.translate
        SingleBannerDesigner.setWindowTitle(_translate("SingleBannerDesigner", "SingleBannerDesigner"))
        SingleBannerDesigner.setStyleSheet(_translate("SingleBannerDesigner", "QGroupBox { font-weight: bold; }"))
        self.BannerColorLabel.setText(_translate("SingleBannerDesigner", "旗帜颜色"))
        self.SaveButton.setText(_translate("SingleBannerDesigner", "保存"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SingleBannerDesigner = QtWidgets.QWidget()
    ui = Ui_SingleBannerDesigner()
    ui.setupUi(SingleBannerDesigner)
    SingleBannerDesigner.show()
    sys.exit(app.exec_())
