# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\SingleBannerDesigner.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SingleBannerDesigner(object):
    def setupUi(self, SingleBannerDesigner):
        SingleBannerDesigner.setObjectName("SingleBannerDesigner")
        SingleBannerDesigner.resize(400, 900)
        self.BannerPainter = QtWidgets.QWidget(SingleBannerDesigner)
        self.BannerPainter.setGeometry(QtCore.QRect(20, 70, 200, 400))
        self.BannerPainter.setObjectName("BannerPainter")
        self.BannerColorComboBox = QtWidgets.QComboBox(SingleBannerDesigner)
        self.BannerColorComboBox.setGeometry(QtCore.QRect(200, 20, 161, 31))
        self.BannerColorComboBox.setObjectName("BannerColorComboBox")
        self.BannerColorLabel = QtWidgets.QLabel(SingleBannerDesigner)
        self.BannerColorLabel.setGeometry(QtCore.QRect(30, 20, 80, 30))
        self.BannerColorLabel.setObjectName("BannerColorLabel")
        self.scrollArea = QtWidgets.QScrollArea(SingleBannerDesigner)
        self.scrollArea.setGeometry(QtCore.QRect(25, 500, 350, 361))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 348, 359))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 351, 711))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.PatternVLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.PatternVLayout.setContentsMargins(0, 0, 0, 0)
        self.PatternVLayout.setObjectName("PatternVLayout")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.UpdateButton = QtWidgets.QPushButton(SingleBannerDesigner)
        self.UpdateButton.setGeometry(QtCore.QRect(260, 400, 100, 61))
        self.UpdateButton.setObjectName("UpdateButton")
        self.UndoButton = QtWidgets.QPushButton(SingleBannerDesigner)
        self.UndoButton.setGeometry(QtCore.QRect(240, 240, 61, 61))
        self.UndoButton.setObjectName("UndoButton")
        self.ReduButton = QtWidgets.QPushButton(SingleBannerDesigner)
        self.ReduButton.setGeometry(QtCore.QRect(320, 240, 61, 61))
        self.ReduButton.setObjectName("ReduButton")
        self.AddButton = QtWidgets.QPushButton(SingleBannerDesigner)
        self.AddButton.setGeometry(QtCore.QRect(260, 70, 100, 61))
        self.AddButton.setObjectName("AddButton")
        self.ClearButton = QtWidgets.QPushButton(SingleBannerDesigner)
        self.ClearButton.setGeometry(QtCore.QRect(260, 150, 100, 61))
        self.ClearButton.setObjectName("ClearButton")
        self.CopyButton = QtWidgets.QPushButton(SingleBannerDesigner)
        self.CopyButton.setGeometry(QtCore.QRect(240, 320, 61, 61))
        self.CopyButton.setObjectName("CopyButton")
        self.PasteButton = QtWidgets.QPushButton(SingleBannerDesigner)
        self.PasteButton.setGeometry(QtCore.QRect(320, 320, 61, 61))
        self.PasteButton.setObjectName("PasteButton")

        self.retranslateUi(SingleBannerDesigner)
        QtCore.QMetaObject.connectSlotsByName(SingleBannerDesigner)

    def retranslateUi(self, SingleBannerDesigner):
        _translate = QtCore.QCoreApplication.translate
        SingleBannerDesigner.setWindowTitle(_translate("SingleBannerDesigner", "SingleBannerDesigner"))
        SingleBannerDesigner.setStyleSheet(_translate("SingleBannerDesigner", "QGroupBox { font-weight: bold; }"))
        self.BannerColorLabel.setText(_translate("SingleBannerDesigner", "旗帜颜色"))
        self.UpdateButton.setText(_translate("SingleBannerDesigner", "更新"))
        self.UndoButton.setText(_translate("SingleBannerDesigner", "撤销"))
        self.ReduButton.setText(_translate("SingleBannerDesigner", "重做"))
        self.AddButton.setText(_translate("SingleBannerDesigner", "添加染色"))
        self.ClearButton.setText(_translate("SingleBannerDesigner", "清除"))
        self.CopyButton.setText(_translate("SingleBannerDesigner", "复制"))
        self.PasteButton.setText(_translate("SingleBannerDesigner", "粘贴"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SingleBannerDesigner = QtWidgets.QWidget()
    ui = Ui_SingleBannerDesigner()
    ui.setupUi(SingleBannerDesigner)
    SingleBannerDesigner.show()
    sys.exit(app.exec_())
