# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ToolBox.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ToolBox(object):
    def setupUi(self, ToolBox):
        ToolBox.setObjectName("ToolBox")
        ToolBox.resize(400, 900)
        self.ToolBoxVLayout = QtWidgets.QVBoxLayout(ToolBox)
        self.ToolBoxVLayout.setObjectName("ToolBoxVLayout")
        self.FileLabel = QtWidgets.QLabel(ToolBox)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.FileLabel.setFont(font)
        self.FileLabel.setObjectName("FileLabel")
        self.ToolBoxVLayout.addWidget(self.FileLabel)
        self.FilePathHintLabel = QtWidgets.QLabel(ToolBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FilePathHintLabel.sizePolicy().hasHeightForWidth())
        self.FilePathHintLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.FilePathHintLabel.setFont(font)
        self.FilePathHintLabel.setObjectName("FilePathHintLabel")
        self.ToolBoxVLayout.addWidget(self.FilePathHintLabel)
        self.FilePathLabel = QtWidgets.QLabel(ToolBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FilePathLabel.sizePolicy().hasHeightForWidth())
        self.FilePathLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.FilePathLabel.setFont(font)
        self.FilePathLabel.setText("")
        self.FilePathLabel.setObjectName("FilePathLabel")
        self.ToolBoxVLayout.addWidget(self.FilePathLabel)
        self.FileButtonGridWidget = QtWidgets.QWidget(ToolBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FileButtonGridWidget.sizePolicy().hasHeightForWidth())
        self.FileButtonGridWidget.setSizePolicy(sizePolicy)
        self.FileButtonGridWidget.setObjectName("FileButtonGridWidget")
        self.FileButtonGrid = QtWidgets.QGridLayout(self.FileButtonGridWidget)
        self.FileButtonGrid.setObjectName("FileButtonGrid")
        self.FileLoadButton = QtWidgets.QPushButton(self.FileButtonGridWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FileLoadButton.sizePolicy().hasHeightForWidth())
        self.FileLoadButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.FileLoadButton.setFont(font)
        self.FileLoadButton.setObjectName("FileLoadButton")
        self.FileButtonGrid.addWidget(self.FileLoadButton, 0, 1, 1, 1)
        self.FileSaveButton = QtWidgets.QPushButton(self.FileButtonGridWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FileSaveButton.sizePolicy().hasHeightForWidth())
        self.FileSaveButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.FileSaveButton.setFont(font)
        self.FileSaveButton.setObjectName("FileSaveButton")
        self.FileButtonGrid.addWidget(self.FileSaveButton, 0, 2, 1, 1)
        self.ToolBoxVLayout.addWidget(self.FileButtonGridWidget)

        self.retranslateUi(ToolBox)
        QtCore.QMetaObject.connectSlotsByName(ToolBox)

    def retranslateUi(self, ToolBox):
        _translate = QtCore.QCoreApplication.translate
        self.FileLabel.setText(_translate("ToolBox", "文件管理"))
        self.FilePathHintLabel.setText(_translate("ToolBox", "当前文件路径："))
        self.FileLoadButton.setText(_translate("ToolBox", "加载文件"))
        self.FileSaveButton.setText(_translate("ToolBox", "保存文件"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ToolBox = QtWidgets.QWidget()
    ui = Ui_ToolBox()
    ui.setupUi(ToolBox)
    ToolBox.show()
    sys.exit(app.exec_())
