# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\PatternSelector.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PatternSelector(object):
    def setupUi(self, PatternSelector):
        PatternSelector.setObjectName("PatternSelector")
        PatternSelector.resize(450, 180)
        self.Index = QtWidgets.QLabel(PatternSelector)
        self.Index.setGeometry(QtCore.QRect(400, 0, 41, 21))
        self.Index.setObjectName("Index")
        self.PatternColorComboBox = QtWidgets.QComboBox(PatternSelector)
        self.PatternColorComboBox.setGeometry(QtCore.QRect(130, 130, 161, 31))
        self.PatternColorComboBox.setObjectName("PatternColorComboBox")
        self.PatternColorLabel = QtWidgets.QLabel(PatternSelector)
        self.PatternColorLabel.setGeometry(QtCore.QRect(30, 130, 80, 30))
        self.PatternColorLabel.setObjectName("PatternColorLabel")
        self.scrollArea = QtWidgets.QScrollArea(PatternSelector)
        self.scrollArea.setGeometry(QtCore.QRect(10, 30, 411, 91))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 409, 89))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayoutWidget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(-1, -1, 411, 91))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.PatternStyleGLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.PatternStyleGLayout.setContentsMargins(0, 0, 0, 0)
        self.PatternStyleGLayout.setObjectName("PatternStyleGLayout")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.PatternColorLabel_2 = QtWidgets.QLabel(PatternSelector)
        self.PatternColorLabel_2.setGeometry(QtCore.QRect(10, 0, 80, 30))
        self.PatternColorLabel_2.setObjectName("PatternColorLabel_2")

        self.retranslateUi(PatternSelector)
        QtCore.QMetaObject.connectSlotsByName(PatternSelector)

    def retranslateUi(self, PatternSelector):
        _translate = QtCore.QCoreApplication.translate
        PatternSelector.setWindowTitle(_translate("PatternSelector", "PatternSelector"))
        PatternSelector.setStyleSheet(_translate("PatternSelector", "QGroupBox { font-weight: bold; }"))
        self.Index.setText(_translate("PatternSelector", "0"))
        self.PatternColorLabel.setText(_translate("PatternSelector", "图案颜色"))
        self.PatternColorLabel_2.setText(_translate("PatternSelector", "图案样式"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PatternSelector = QtWidgets.QWidget()
    ui = Ui_PatternSelector()
    ui.setupUi(PatternSelector)
    PatternSelector.show()
    sys.exit(app.exec_())
